### ISSUE TITLE
'shell' template? 

### ISSUE THREAD

**Issue by winchendonsprings** [chriskempson/base16-xresources#10]
What does this mean?

! Note: colors beyond 15 might not be loaded (e.g., xterm, urxvt),
! use 'shell' template to set these if necessary

I'm struggling to get my colors to display properly for urxvt. (rxvt-unicode-256color)

Using ./colortest from base16-shell shows the extra blue colors rather than grey shades. The scripts in base16-shell to set the colors do not agree when set in zshrc.

**Comment by kepi** [comment]
I think author is referring to https://github.com/chriskempson/base16-shell. So instead (or in addition to ) of using Xresources you simply run base16-shell script which will set your terminal colors and colortest then works as it should.

**Comment by chriskempson** [comment]
Is this issue resolved now?

**Comment by winchendonsprings** [comment]
resolved

**Comment by chriskempson** [comment]
Thanks, I'll close this issue then.

**Comment by tnguyen14** [comment]
Do I still need to use this `.Xresources` file if I'm using `base16-shell`?
