### ISSUE TITLE
Invalid use of wildcards

### ISSUE THREAD

**Issue by krumelmonster** [chriskempson/base16-xresources#23]
According to [the X manpage](https://www.x.org/archive/X11R6.7.0/doc/X.7.html#sect13), Wildcards in Xresources have to be followed by a character or '?'.

**Comment by omtcyfz** [comment]
https://github.com/chriskempson/base16-xresources/pull/24 is merged, should this issue be closed?

**Comment by chriskempson** [comment]
Yep
