### ISSUE TITLE
Wrong colors

### ISSUE THREAD

**Issue by nmeum** [chriskempson/base16-xresources#7]
Somehow the colorscheme for 'base16-default.dark.xresources' seems to be completly broken.

I am using urxvt and [this](http://i.imgur.com/PybOOsX.png) is what my urxvt looks like with the xresources mentioned above. [This](http://i.imgur.com/hRJfFEn.png) is what urxvt is supposed to like according to the spec. As you can see the colors are completly different. Thus almost all applications look completly wrong, for instance [vim](http://i.imgur.com/f6ohC13.png). And yes, I didn't define the `base16colorspace` variable in vim.

I went looked at some of the closed and open issues of the base16-* repositories and the maintainer seems to have the opinion that one should use base16-shell instead of the Xresources file. However, I am of the opinion that this is a stupid idea. The Xresources file is the way to go if you wanna write a colorschme, using a shell script to do so is just a dirty hack. I think that the Xresources file should be fixed instead of telling people to use base16-shell instead.

I am running urxvt with the following version and options:

```
rxvt-unicode (urxvt) v9.20 - released: 2014-04-26
options: perl,xft,styles,combining,blink,iso14755,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,pixbuf,XIM,frills,selectionscrolling,wheel,slipwheel,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
```

**Comment by yusiwen** [comment]
Which 256 colors Xresouces schemes should I use to prevent bright vim problem? I currently use default.dark.256.xresources, source `base16-default.dark.sh`, and the output of `colortest` is just the same as yours, but vim is still so bright.

**Comment by blueyed** [comment]
This issue by itself can be closed probably?!
